export const START_FETCHING_USER: string = 'USER/START_FETCHING_USER'
export const ERROR_FETCHING_USER: string = 'USER/ERROR_FETCHING_USER'
export const SUCCESS_FETCHING_USER: string = 'USER/SUCCESS_FETCHING_USER'
