export const START_FETCHING_REPOS: string = 'REPOS/START_FETCHING_REPOS'
export const ERROR_FETCHING_REPOS: string = 'REPOS/ERROR_FETCHING_REPOS'
export const SUCCESS_FETCHING_REPOS: string = 'REPOS/SUCCESS_FETCHING_REPOS'
export const RESET_REPOS: string = 'REPOS/RESET_REPOS'
